const pizzas=[
{id:'margherita',name:'Margherita 72',price:16,image:'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1200&q=85',alt:'Margherita pizza with basil',description:'San Marzano tomatoes, fresh mozzarella, Parmigiano Reggiano, basil, extra virgin olive oil.'},
{id:'soppressata',name:'Spicy Soppressata',price:21,image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=85',alt:'Spicy soppressata pizza',description:'Tomato, mozzarella, spicy soppressata, Calabrian chili, hot honey.'},
{id:'truffle',name:'Truffle Bianca',price:24,image:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1200&q=85',alt:'White truffle and mushroom pizza',description:'Fior di latte, mushrooms, truffle cream, Parmigiano, fresh thyme.'},
{id:'prosciutto',name:'Prosciutto & Burrata',price:25,image:'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=1200&q=85',alt:'Prosciutto and burrata pizza',description:'Tomato, prosciutto di Parma, burrata, arugula, Parmigiano.'},
{id:'diavola',name:'Diavola',price:22,image:'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=1200&q=85',alt:'Spicy salami Diavola pizza',description:'Tomato, mozzarella, spicy salami, chili oil, roasted peppers.'},
{id:'funghi',name:'Funghi',price:20,image:'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=1200&q=85',alt:'Mushroom pizza with parsley',description:'Fior di latte, roasted mushrooms, garlic, Parmigiano, parsley.'}
];
const menu={appetizers:[['Burrata & Tomato',14,'Creamy burrata, heirloom tomato, basil oil.'],['Garlic Knots',9,'Wood-fired, garlic butter, Parmigiano.'],['Meatballs',13,'Beef and pork, San Marzano, ricotta.']],salads:[['Caesar',12,'Romaine, Parmigiano, pangrattato, house dressing.'],['Arugula & Parmigiano',13,'Lemon, olive oil, shaved Parmigiano.'],['Forno Chopped Salad',15,'Olives, peppers, chickpeas, provolone.']],desserts:[['Tiramisu',9,'Mascarpone, espresso, cocoa.'],['Cannoli',8,'Sweet ricotta, pistachio, orange.'],['Nutella Pizza',12,'Hazelnut spread, sea salt, powdered sugar.']],drinks:[['Sparkling Water',4,'Chilled 750ml bottle.'],['Italian Soda',5,'Blood orange or lemon.'],['Coca-Cola',4,'Classic glass bottle.'],['Espresso',4,'Double shot.'],['San Pellegrino',5,'Chilled 750ml bottle.']]};
const builderOptions={size:[['Personal',12],['Regular',16],['Large',20]],crust:[['72-Hour Classic',0],['Thin & Crispy',0],['Gluten-Friendly',3]],sauce:[['San Marzano Tomato',0],['Spicy Tomato',1],['Garlic Bianca',2],['No Sauce',0]],cheese:[['Fresh Mozzarella',0],['Fior di Latte',2],['Vegan Mozzarella',3],['Burrata',5]],toppings:{Meats:[['Pepperoni',3],['Soppressata',4],['Italian Sausage',4],['Prosciutto',5],['Chicken',4]],Vegetables:[['Mushrooms',2],['Roasted Peppers',2],['Red Onion',1.5],['Olives',2],['Jalapeños',1.5],['Artichokes',3],['Arugula',2]],Finishes:[['Hot Honey',1.5],['Truffle Oil',3],['Chili Oil',1],['Parmigiano',2],['Fresh Basil',1]]}};

let cart=JSON.parse(localStorage.getItem('forno72-cart')||'[]'),selectedTime='',fulfillment='pickup';
const money=value=>`$${value.toFixed(2)}`;
const toast=message=>{const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),1800)};

function renderPizzas(){document.querySelector('#pizza-grid').innerHTML=pizzas.map((pizza,index)=>`<article class="pizza-card" data-product="${pizza.id}" tabindex="0" aria-label="View ${pizza.name}"><img src="${pizza.image}" alt="${pizza.alt}"><div><span>${String(index+1).padStart(2,'0')}</span><h3>${pizza.name}</h3><p>${pizza.description}</p><footer><b>$${pizza.price}</b><button data-add="${pizza.id}" aria-label="Add ${pizza.name}">Add to order +</button></footer></div></article>`).join('')}
function renderMenu(category='appetizers'){document.querySelector('#menu-list').innerHTML=menu[category].map(([name,price,description])=>`<article class="menu-item"><h3>${name}</h3><p>${description}</p><button data-menu-add="${name}" data-price="${price}" aria-label="Add ${name}">$${price} +</button></article>`).join('')}
function addToCart(item){const existing=cart.find(entry=>entry.key===item.key);if(existing)existing.quantity+=1;else cart.push({...item,quantity:1});saveCart();toast(`${item.name} added to your order`)}
function saveCart(){localStorage.setItem('forno72-cart',JSON.stringify(cart));renderCart()}
function renderCart(){document.querySelector('#cart-count').textContent=cart.reduce((sum,item)=>sum+item.quantity,0);const container=document.querySelector('#cart-items');container.innerHTML=cart.length?cart.map(item=>`<article class="cart-item"><div><h3>${item.name}</h3><p>${item.options?.join(' · ')||'Forno favorite'}</p></div><b>${money(item.price*item.quantity)}</b><div class="qty"><button data-qty="${item.key}" data-delta="-1" aria-label="Decrease ${item.name}">−</button><span>${item.quantity}</span><button data-qty="${item.key}" data-delta="1" aria-label="Increase ${item.name}">+</button></div><button class="remove" data-remove="${item.key}">Remove</button></article>`).join(''):'<div class="empty-cart"><p class="eyebrow red">Nothing here yet</p><h3>Your oven is waiting.</h3><p>Add a Forno favorite or build your own pizza.</p></div>';const subtotal=cart.reduce((sum,item)=>sum+item.price*item.quantity,0),tax=subtotal*.07;document.querySelector('#cart-subtotal').textContent=money(subtotal);document.querySelector('#cart-tax').textContent=money(tax);document.querySelector('#cart-total').textContent=money(subtotal+tax);document.querySelector('#checkout-button').disabled=!cart.length}
function openCart(open=true){document.querySelector('#cart-drawer').classList.toggle('open',open);document.querySelector('#cart-drawer').setAttribute('aria-hidden',String(!open));document.querySelector('#cart-overlay').hidden=!open;document.body.classList.toggle('no-scroll',open)}
function openProduct(id){const pizza=pizzas.find(item=>item.id===id),dialog=document.querySelector('#product-dialog');document.querySelector('#product-detail').innerHTML=`<div class="product-detail"><img src="${pizza.image}" alt="${pizza.alt}"><div><p class="eyebrow red">Forno favorite</p><h2>${pizza.name}</h2><p>${pizza.description}</p><p>Built on our signature 72-hour fermented dough and fired at extreme heat for a light, blistered crust.</p><div class="price">$${pizza.price}</div><button class="button button-red" data-dialog-add="${pizza.id}">Add to order — $${pizza.price}</button></div></div>`;dialog.showModal()}
function optionMarkup(group,items,defaultIndex=0){return items.map(([name,price],index)=>`<label class="choice"><input type="radio" name="${group}" value="${name}" data-price="${price}" ${index===defaultIndex?'checked':''}><span><strong>${name}</strong><em>${price?`+${money(price)}`:'Included'}</em></span></label>`).join('')}
function setupBuilder(){document.querySelector('#size-options').innerHTML=optionMarkup('size',builderOptions.size,1);document.querySelector('#crust-options').innerHTML=optionMarkup('crust',builderOptions.crust);document.querySelector('#sauce-options').innerHTML=optionMarkup('sauce',builderOptions.sauce);document.querySelector('#cheese-options').innerHTML=optionMarkup('cheese',builderOptions.cheese);document.querySelector('#topping-options').innerHTML=Object.entries(builderOptions.toppings).map(([group,items])=>`<div class="topping-group"><h4>${group}</h4><div class="topping-grid">${items.map(([name,price])=>`<label class="choice"><input type="checkbox" name="topping" value="${name}" data-price="${price}"><span><strong>${name}</strong><em>+${money(price)}</em></span></label>`).join('')}</div></div>`).join('');document.querySelector('#pizza-builder').addEventListener('change',updateBuilder);updateBuilder()}
function builderSelection(){const form=new FormData(document.querySelector('#pizza-builder')),entries=[...document.querySelectorAll('#pizza-builder input:checked')];return{size:form.get('size'),crust:form.get('crust'),sauce:form.get('sauce'),cheese:form.get('cheese'),toppings:form.getAll('topping'),price:entries.reduce((sum,input)=>sum+Number(input.dataset.price),0)}}
function updateBuilder(){const pick=builderSelection(),options=[pick.crust,pick.sauce,pick.cheese,...pick.toppings];document.querySelector('#builder-name').textContent=`${pick.size} · ${pick.crust.replace('72-Hour ','')}`;document.querySelector('#builder-summary').innerHTML=options.map(value=>`<li>${value}</li>`).join('');document.querySelector('#builder-price').textContent=money(pick.price);document.querySelector('#add-custom').textContent=`Add to order — ${money(pick.price)}`}
function reservationConfirmation(data,code){const date=new Date(`${data.date}T12:00:00`).toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});document.querySelector('#reservation-form').innerHTML=`<div class="confirmation"><div><p class="eyebrow red">Reservation confirmed</p><h2>TABLE BOOKED.</h2><p>${date}<br><strong>${data.time}</strong><br>${data.party}</p><p class="order-number">Reservation #${code}</p><p>We sent the details to ${data.email}.</p></div></div>`}
function checkout(){if(!cart.length)return;const dialog=document.querySelector('#checkout-dialog');document.querySelector('#checkout-summary').innerHTML=`<p class="eyebrow">Your order</p>${cart.map(item=>`<div class="checkout-summary-item"><span>${item.quantity}× ${item.name}</span><b>${money(item.price*item.quantity)}</b></div>`).join('')}<div class="checkout-summary-total"><span>Total</span><b>${document.querySelector('#cart-total').textContent}</b></div>`;openCart(false);dialog.showModal()}

document.addEventListener('click',event=>{const add=event.target.closest('[data-add]');if(add){event.stopPropagation();const pizza=pizzas.find(item=>item.id===add.dataset.add);addToCart({key:pizza.id,name:pizza.name,price:pizza.price})}const card=event.target.closest('[data-product]');if(card&&!add)openProduct(card.dataset.product);const menuAdd=event.target.closest('[data-menu-add]');if(menuAdd)addToCart({key:`menu-${menuAdd.dataset.menuAdd}`,name:menuAdd.dataset.menuAdd,price:Number(menuAdd.dataset.price)});const tab=event.target.closest('[data-category]');if(tab){document.querySelectorAll('.menu-tabs button').forEach(b=>b.classList.toggle('active',b===tab));renderMenu(tab.dataset.category)}const dialogAdd=event.target.closest('[data-dialog-add]');if(dialogAdd){const pizza=pizzas.find(item=>item.id===dialogAdd.dataset.dialogAdd);addToCart({key:pizza.id,name:pizza.name,price:pizza.price});document.querySelector('#product-dialog').close()}if(event.target.closest('.dialog-close')&&!event.target.closest('.checkout-close'))document.querySelector('#product-dialog').close();if(event.target.closest('.checkout-close'))document.querySelector('#checkout-dialog').close();const qty=event.target.closest('[data-qty]');if(qty){const item=cart.find(entry=>entry.key===qty.dataset.qty);item.quantity+=Number(qty.dataset.delta);if(item.quantity<=0)cart=cart.filter(entry=>entry.key!==item.key);saveCart()}const remove=event.target.closest('[data-remove]');if(remove){cart=cart.filter(item=>item.key!==remove.dataset.remove);saveCart()}});
document.querySelector('.cart-trigger').addEventListener('click',()=>openCart());document.querySelector('.close-cart').addEventListener('click',()=>openCart(false));document.querySelector('#cart-overlay').addEventListener('click',()=>openCart(false));document.querySelector('#checkout-button').addEventListener('click',checkout);
document.querySelector('#add-custom').addEventListener('click',()=>{const pick=builderSelection(),options=[pick.size,pick.crust,pick.sauce,pick.cheese,...pick.toppings];addToCart({key:`custom-${Date.now()}`,name:'Your Pizza',price:pick.price,options});openCart()});
document.querySelector('.menu-toggle').addEventListener('click',event=>{const nav=document.querySelector('#main-nav'),open=nav.classList.toggle('open');event.currentTarget.setAttribute('aria-expanded',String(open))});document.querySelectorAll('#main-nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('#main-nav').classList.remove('open')));window.addEventListener('scroll',()=>document.querySelector('.site-header').classList.toggle('scrolled',scrollY>50));
const dateInput=document.querySelector('[name="date"]');dateInput.min=new Date().toISOString().slice(0,10);const times=['5:00 PM','5:30 PM','6:00 PM','6:30 PM','7:00 PM','7:30 PM','8:00 PM','8:30 PM','9:00 PM'];document.querySelector('#time-grid').innerHTML=times.map(time=>`<button type="button" data-time="${time}">${time}</button>`).join('');document.querySelector('#time-grid').addEventListener('click',event=>{const button=event.target.closest('[data-time]');if(!button)return;selectedTime=button.dataset.time;document.querySelectorAll('[data-time]').forEach(b=>b.classList.toggle('active',b===button));document.querySelector('#guest-details').classList.add('enabled')});
document.querySelector('#reservation-form').addEventListener('submit',event=>{event.preventDefault();if(!selectedTime){toast('Choose an available time');return}const form=new FormData(event.currentTarget),data=Object.fromEntries(form);data.time=selectedTime;const code=`F72R-${Math.floor(1000+Math.random()*9000)}`,reservations=JSON.parse(localStorage.getItem('forno72-reservations')||'[]');reservations.push({...data,code});localStorage.setItem('forno72-reservations',JSON.stringify(reservations));reservationConfirmation(data,code)});
document.querySelectorAll('.fulfillment-toggle button').forEach(button=>button.addEventListener('click',()=>{fulfillment=button.dataset.type;document.querySelectorAll('.fulfillment-toggle button').forEach(b=>b.classList.toggle('active',b===button));const delivery=document.querySelector('#delivery-fields');delivery.hidden=fulfillment!=='delivery';delivery.querySelectorAll('input').forEach(input=>input.required=fulfillment==='delivery'&&!['apartment','instructions'].includes(input.name));document.querySelector('#pickup-fields').hidden=fulfillment==='delivery'}));
document.querySelector('#checkout-form').addEventListener('submit',event=>{event.preventDefault();const code=`F72-${Math.floor(1000+Math.random()*9000)}`,eta=fulfillment==='pickup'?'25–35 minutes':'40–55 minutes';cart=[];saveCart();document.querySelector('#checkout-view').innerHTML=`<div class="confirmation"><div><p class="eyebrow red">Order confirmed</p><h2>YOUR PIZZA IS<br>IN THE WORKS.</h2><p class="order-number">Order #${code}</p><p>Estimated ${fulfillment} time<br><strong>${eta}</strong></p><button class="button button-red" onclick="document.querySelector('#checkout-dialog').close()">Back to Forno 72</button></div></div>`});
document.querySelectorAll('.quote-dots button').forEach((button,index)=>button.addEventListener('click',()=>{document.querySelectorAll('.quote').forEach((quote,i)=>quote.classList.toggle('active',i===index));document.querySelectorAll('.quote-dots button').forEach((dot,i)=>dot.classList.toggle('active',i===index))}));document.querySelector('.pizza-grid').addEventListener('keydown',event=>{const card=event.target.closest('[data-product]');if(card&&(event.key==='Enter'||event.key===' ')){event.preventDefault();openProduct(card.dataset.product)}});
renderPizzas();renderMenu();setupBuilder();renderCart();
const schema=document.createElement('script');schema.type='application/ld+json';schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':['Restaurant','LocalBusiness'],name:'Forno 72',description:'Artisan Neapolitan pizza made with 72-hour fermented dough.',servesCuisine:'Italian, Neapolitan Pizza',telephone:'+1-305-555-0172',email:'ciao@forno72.com',address:{'@type':'PostalAddress',streetAddress:'728 NE 2nd Avenue',addressLocality:'Miami',addressRegion:'FL',postalCode:'33132'},hasMenu:{'@type':'Menu',name:'Forno 72 Menu'}});document.head.appendChild(schema);

